site_name: Relatório do Programa De Tutoria de Aprendizagem e Laboratório
site_author: Leonardo Furtado Kauffmann

# O plugin mermaid2, usado para renderizar diagramas mermaid,
# só funciona com o tema material.
theme:
  name: material
  language: pt

markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom


plugins:
    - search
    - mermaid2
